# Generated by Django 5.0.2 on 2024-05-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='JoiningDate',
            field=models.CharField(max_length=25),
        ),
    ]
