# Generated by Django 5.0.2 on 2024-05-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_alter_studentdata_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='PG_CGPA',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='PG_Year',
            field=models.CharField(max_length=25),
        ),
    ]
