# Generated by Django 5.0.2 on 2024-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_alter_studentdata_pg_cgpa_alter_studentdata_pg_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Degree_CGPA',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Inter_CGPA',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='SSC_CGPA',
            field=models.CharField(max_length=25),
        ),
    ]
