# Generated by Django 5.0.2 on 2024-05-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_alter_studentdata_degree_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Phone',
            field=models.CharField(max_length=25),
        ),
    ]
