# Generated by Django 5.0.2 on 2024-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0005_alter_studentdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Degree_Year',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Inter_Year',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='SSC_Year',
            field=models.CharField(max_length=25),
        ),
    ]
