# Generated by Django 5.0.2 on 2024-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0006_alter_studentdata_degree_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdata',
            name='CaseStudies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='Classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='Interviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='MockTests',
            field=models.IntegerField(default=0),
        ),
    ]
