# Generated by Django 5.0.2 on 2024-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0007_alter_batchdata_casestudies_alter_batchdata_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=25)),
            ],
        ),
    ]
