# Generated by Django 5.0.2 on 2024-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0010_alter_studentdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datedata',
            name='CaseStudyDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datedata',
            name='ClassDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datedata',
            name='InterviewDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datedata',
            name='MockTestDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
