# Generated by Django 5.0.2 on 2024-05-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0011_alter_datedata_casestudydate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datedata',
            old_name='CaseStudyDate',
            new_name='BatchDates',
        ),
        migrations.RemoveField(
            model_name='datedata',
            name='ClassDate',
        ),
        migrations.RemoveField(
            model_name='datedata',
            name='InterviewDate',
        ),
        migrations.RemoveField(
            model_name='datedata',
            name='MockTestDate',
        ),
    ]
