# Generated by Django 5.0.2 on 2024-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0012_rename_casestudydate_datedata_batchdates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datedata',
            name='BatchDates',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
