# Generated by Django 5.0.2 on 2024-05-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0013_alter_datedata_batchdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='CaseStudies',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Classes',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Interviews',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='MockTests',
            field=models.CharField(max_length=25),
        ),
    ]
