# Generated by Django 5.0.2 on 2024-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0014_alter_studentdata_casestudies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='CaseStudies',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Classes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Interviews',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='MockTests',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Project',
            field=models.CharField(max_length=255),
        ),
    ]
