# Generated by Django 5.0.2 on 2024-05-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0015_alter_studentdata_casestudies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdata',
            name='CaseStudies',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='Classes',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='Interviews',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchdata',
            name='MockTests',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
