# Generated by Django 5.0.2 on 2024-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0016_alter_batchdata_casestudies_alter_batchdata_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('OTP', models.CharField(max_length=255)),
            ],
        ),
    ]
