# Generated by Django 5.0.2 on 2024-05-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0017_sendotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='Email',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
