# Generated by Django 5.0.2 on 2024-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0018_logindata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='Status',
            field=models.CharField(default='Deactive', max_length=25),
        ),
    ]
