# Generated by Django 5.0.2 on 2024-05-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0019_logindata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='Permission',
            field=models.CharField(default='Denied', max_length=25),
        ),
    ]
