# Generated by Django 5.0.2 on 2024-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0021_logindata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='Status',
        ),
    ]
